const tips = [
    "Use energy-efficient LED lights in your office.",
    "Turn off devices when not in use.",
    "Recycle your electronics and e-waste.",
    "Support companies that use renewable energy.",
    "Implement a paperless workflow wherever possible.",
    "Use cloud services to optimize resource usage.",
    "Reduce the number of physical devices by consolidating workloads.",
    "Install energy-efficient cooling systems in data centers.",
    "Optimize the efficiency of your software to reduce power consumption.",
    "Switch to electric vehicles for company fleets.",
    "Turn down the brightness of your screen to save power.",
    "Recycle your old tech gadgets responsibly.",
    "Switch to a green energy provider for your data center.",
    "Use a green browser plugin to reduce your carbon footprint.",
    "Embrace open-source software to avoid proprietary waste.",
    "Use rechargeable batteries instead of disposable ones.",
    "Unplug devices when they're not in use to avoid phantom energy consumption.",
    "Use dual-monitor setups efficiently to reduce the number of devices.",
    "Choose energy-efficient computers and peripherals.",
    "Use virtual meetings to reduce travel-related carbon emissions.",
    "Go paperless with invoices, receipts, and communication.",
    "Reduce the number of emails you send by consolidating communication.",
    "Use a green hosting service for your website.",
    "Make your website load faster by optimizing images and scripts, reducing server demand.",
    "Switch off unnecessary background applications on your computer.",
    "Reuse old cables and adapters instead of buying new ones.",
    "Choose sustainable office supplies like recycled paper and biodegradable pens.",
    "Replace your desktop wallpaper with a nature scene to inspire sustainability.",
    "Encourage your team to work from home to reduce commuting-related emissions.",
    "Use digital signatures instead of printing out documents for signing.",
    "Take advantage of remote collaboration tools to avoid business travel.",
    "Choose eco-friendly packaging for shipping products.",
    "Use solar panels to power your office or home office.",
    "Avoid single-use plastic by opting for reusable bags and containers.",
    "Implement a 'bring your own cup' policy in your office.",
    "Make a habit of turning off your computer overnight.",
    "Use a smaller device when possible to reduce energy consumption (e.g., tablets over laptops).",
    "Choose energy-efficient air conditioning and heating systems.",
    "Invest in low-carbon-footprint office equipment.",
    "Turn off lights when leaving a room to save energy.",
    "Use natural light during the day instead of artificial lighting.",
    "Recycle your old printer cartridges.",
    "Choose companies with sustainability certifications when purchasing tech.",
    "Use power strips for all electronics and turn them off when not in use.",
    "Avoid auto-play videos on websites to save data and power.",
    "Support the use of sustainable and eco-friendly IT equipment.",
    "Encourage the use of carpooling and public transportation among employees.",
    "Recycle electronic devices responsibly through certified recycling centers.",
    "Choose digital invoices and bills instead of paper ones.",
    "Opt for digital books over printed books when possible.",
    "Use rechargeable electric gadgets instead of disposable ones.",
    "Choose server locations close to your customer base to reduce energy loss during transmission.",
    "Use energy-efficient virtual machines on your servers.",
    "Use a laptop over a desktop when possible for energy savings.",
    "Implement green building standards in your office space.",
    "Support businesses that are committed to reducing carbon emissions.",
    "Opt for a virtual desktop infrastructure (VDI) solution to reduce hardware needs.",
    "Use energy-efficient routers and modems for your network.",
    "Host your website on servers with a carbon-neutral certification.",
    "Opt for sustainable business travel options such as trains over planes.",
    "Encourage recycling programs in your office.",
    "Install motion sensors in your office to control lighting automatically.",
    "Choose sustainable web design practices that reduce server load.",
    "Support eco-friendly data center initiatives.",
    "Donate your old tech equipment to schools or non-profits instead of throwing it away.",
    "Use compostable office supplies like paper cups and plates.",
    "Choose electric or hybrid vehicles for business transportation.",
    "Educate employees about reducing paper waste in the office.",
    "Install energy-saving power management tools on your devices.",
    "Encourage employees to bring reusable water bottles and cups to work.",
    "Use digital collaboration tools to reduce the need for paper documents.",
    "Buy second-hand tech products to reduce demand for new electronics.",
    "Use tools to analyze and reduce your website’s carbon footprint.",
    "Avoid leaving your computer on standby when not in use.",
    "Choose sustainable office furniture made from recycled or renewable materials.",
    "Consider using biodegradable packaging for products.",
    "Implement smart thermostats in your office to reduce energy use.",
    "Install water-saving devices in your office’s restrooms.",
    "Organize electronic recycling drives in your community.",
    "Use sustainable hosting services for your website to minimize energy use.",
    "Advocate for the use of renewable energy in the tech industry.",
    "Encourage your company to adopt a zero-waste policy.",
    "Reduce the size of your website to reduce energy consumption.",
    "Minimize your office’s carbon footprint by encouraging telecommuting.",
    "Reduce plastic waste by using digital receipts.",
    "Offset your company’s carbon emissions through certified carbon offset programs.",
    "Use the 'dark mode' setting on apps and devices to save power.",
    "Invest in eco-friendly cooling solutions for your data center.",
    "Educate your team on responsible tech usage and sustainability.",
    "Encourage your team to adopt minimalistic tech setups.",
    "Use sustainable materials like bamboo for office products.",
    "Replace plastic packaging with compostable or recyclable alternatives.",
    "Establish a company-wide sustainability initiative.",
    "Invest in an eco-friendly website design.",
    "Monitor and optimize the energy consumption of your digital tools.",
    "Use blockchain technology for sustainable supply chains.",
    "Implement cloud computing to reduce your office’s physical infrastructure.",
    "Consider building your own green data center.",
    "Participate in tree planting programs and environmental conservation projects.",
    "Adopt a circular economy model by reusing and recycling tech products.",
    "Encourage the development of low-energy apps and digital tools."
];
